FROM emscripten/emsdk:4.0.6-arm64

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake

WORKDIR /app

COPY . .

RUN rm -rf build

RUN emcmake cmake -S . -B build

RUN cmake --build build

EXPOSE 8000

CMD ["python3", "-m", "http.server"]
